### PR TITLE
uploading hasSBOMs for guacdiff tests in guacsec/guac

### PR DESCRIPTION
**Pull request by yoarora**
These files are hasSBOM structs marshalled to JSON to aid testing of guacanalyze/guacdiff in guacsec/guac.

### CODE REVIEW

**Comment by yoarora** [comment]
@nathannaveen Please review and merge when you are able to. Thanks.

**Review by mihaimaruseac — APPROVED** [review]

**Comment by nathannaveen** [comment]
Hey @arorasoham9 could you also move `pkg/analyzer/test_HasSBOMs_diff.json` from your PR in guacsec/guac to this test repo?

**Comment by yoarora** [comment]
@nathannaveen Yes, I can. The modified code in [this](https://github.com/guacsec/guac/pull/1809) PR is dependent on this PR to be merged for the CI to pass. I am just waiting for this PR to be merged before I send in those commits with the removed `pkg/analyzer/test_HasSBOMs_diff.json` file. If that makes sense.

**Comment by yoarora** [comment]
@nathannaveen I anyway pushed the last commit. You will see the `pkg/analyzer/test_HasSBOMs_diff.json` file removed now.

**Review by nathannaveen — APPROVED** [review]
Ok, yeah, that makes sense. Thank you!

**Pull request merged**
